In [3]:
import codecs
import json

def read_dataset(path):
  with codecs.open(path, 'r', 'utf-8') as myFile:
    content = myFile.read()
  dataset = json.loads(content)
  return dataset

if __name__ == '__main__':
  path = 'pizza_request_dataset.json'
  dataset = read_dataset(path)

In [6]:
print ('The dataset contains %d samples.' %(len(dataset)))

The dataset contains 5671 samples.


In [7]:
print ('Available attributes: ', sorted(dataset[0].keys()))

Available attributes:  ['giver_username_if_known', 'in_test_set', 'number_of_downvotes_of_request_at_retrieval', 'number_of_upvotes_of_request_at_retrieval', 'post_was_edited', 'request_id', 'request_number_of_comments_at_retrieval', 'request_text', 'request_text_edit_aware', 'request_title', 'requester_account_age_in_days_at_request', 'requester_account_age_in_days_at_retrieval', 'requester_days_since_first_post_on_raop_at_request', 'requester_days_since_first_post_on_raop_at_retrieval', 'requester_number_of_comments_at_request', 'requester_number_of_comments_at_retrieval', 'requester_number_of_comments_in_raop_at_request', 'requester_number_of_comments_in_raop_at_retrieval', 'requester_number_of_posts_at_request', 'requester_number_of_posts_at_retrieval', 'requester_number_of_posts_on_raop_at_request', 'requester_number_of_posts_on_raop_at_retrieval', 'requester_number_of_subreddits_at_request', 'requester_received_pizza', 'requester_subreddits_at_request', 'requester_upvotes_minus_d

In [9]:
print ('First post:')
print (json.dumps(dataset[0], sort_keys=True, indent=2))

First post:
{
  "giver_username_if_known": "N/A",
  "in_test_set": false,
  "number_of_downvotes_of_request_at_retrieval": 2,
  "number_of_upvotes_of_request_at_retrieval": 6,
  "post_was_edited": false,
  "request_id": "t3_w5491",
  "request_number_of_comments_at_retrieval": 7,
  "request_text": "I'm not in College, or a starving artist or anything like that. I've just been a bit unlucky lately. I'm a 36 year old single guy with a job. But rent, and other bills killed me this month. I thought I had enough funds in my account to at least keep me set with Mr. Noodles, I forgot about my monthly banking fee.\n\nI had a small bag of chips Wednesday afternoon, and I get paid Monday, so I'll be fine then.. It's just really painful at this point and food is something I'm constantly thinking about.\n\nI've got a few bucks to get on the bus to work on Saturday, so I can't really use that.\n\nI'm really embarrassed to even be asking like this and I'm not sure how it works, so please be patient w

In [10]:
successes = [r['requester_received_pizza'] for r in dataset]
successes

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,

In [12]:
success_rate = 100.0 * sum(successes) / float(len(successes))
print ('The average success rate is: %.2f%%' %(success_rate))

The average success rate is: 24.63%


# Model 1 – n-grams

In [4]:
#Start Assignment 2

import pandas as pd
import numpy as np
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
SENT_DETECTOR = nltk.data.load('tokenizers/punkt/english.pickle')
#from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import model_selection, svm
from sklearn.metrics import accuracy_score

from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\klass\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\klass\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\klass\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\klass\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\klass\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
df = pd.read_json('pizza_request_dataset.json')
df.head()

giver_username_if_known  in_test_set  \
0                     N/A        False   
1                     N/A        False   
2                     N/A        False   
3                     N/A        False   
4                     N/A        False   

   number_of_downvotes_of_request_at_retrieval  \
0                                            2   
1                                            2   
2                                            1   
3                                            2   
4                                            1   

   number_of_upvotes_of_request_at_retrieval  post_was_edited request_id  \
0                                          6                0   t3_w5491   
1                                          6                1   t3_qysgy   
2                                          4                1   t3_if0ed   
3                                         13                0   t3_jr3w1   
4                                          4       1366847814  t3_1d18tc   

   request_number_of_comments_at_retrieval  \
0                                        7   
1                                        8   
2                                        1   
3                                        3   
4                                        5   

                                        request_text  \
0  I'm not in College, or a starving artist or an...   
1  Hello! It's been a hard 2 months with money an...   
2  I'm sure there are needier people on this subr...   
3  I've been unemployed going on three months now...   
4  I ran out of money on my meal card a while bac...   

                             request_text_edit_aware  \
0  I'm not in College, or a starving artist or an...   
1  Hello! It's been a hard 2 months with money an...   
2  I'm sure there are needier people on this subr...   
3  I've been unemployed going on three months now...   
4  I ran out of money on my meal card a while bac...   

                                       request_title  ...  \
0  [Request] Ontario, Canada - On my 3rd of 5 day...  ...   
1   [REQUEST] Southern Arizona, Tucson Hungry Family  ...   
2        [Request] Pizza for a broke college student  ...   
3  [Request] Unemployed and Sick of Rice (Suffolk...  ...   
4  [Request] Ohio USA, broke student musician in ...  ...   

   requester_received_pizza  \
0                      True   
1                      True   
2                      True   
3                      True   
4                      True   

                     requester_subreddits_at_request  \
0  [AdviceAnimals, WTF, funny, gaming, movies, te...   
1                                        [aww, pics]   
2  [AskReddit, DoesAnybodyElse, IAmA, Marijuana, ...   
3  [AdviceAnimals, Art, AskReddit, BookCollecting...   
4                      [TrueAtheism, atheism, funny]   

   requester_upvotes_minus_downvotes_at_request  \
0                                            32   
1                                             5   
2                                          1359   
3                                          1205   
4                                            81   

   requester_upvotes_minus_downvotes_at_retrieval  \
0                                             212   
1                                              21   
2                                            2110   
3                                            4889   
4                                              86   

   requester_upvotes_plus_downvotes_at_request  \
0                                           48   
1                                           13   
2                                         2423   
3                                         2403   
4                                          225   

   requester_upvotes_plus_downvotes_at_retrieval  requester_user_flair  \
0                                            610                shroom   
1                                             57                shroom   


In [6]:
# Model 1 – n-grams

# Change all the text to lower case
df['request_text'] = [post.lower() for post in df['request_text']]
df.head()

giver_username_if_known  in_test_set  \
0                     N/A        False   
1                     N/A        False   
2                     N/A        False   
3                     N/A        False   
4                     N/A        False   

   number_of_downvotes_of_request_at_retrieval  \
0                                            2   
1                                            2   
2                                            1   
3                                            2   
4                                            1   

   number_of_upvotes_of_request_at_retrieval  post_was_edited request_id  \
0                                          6                0   t3_w5491   
1                                          6                1   t3_qysgy   
2                                          4                1   t3_if0ed   
3                                         13                0   t3_jr3w1   
4                                          4       1366847814  t3_1d18tc   

   request_number_of_comments_at_retrieval  \
0                                        7   
1                                        8   
2                                        1   
3                                        3   
4                                        5   

                                        request_text  \
0  i'm not in college, or a starving artist or an...   
1  hello! it's been a hard 2 months with money an...   
2  i'm sure there are needier people on this subr...   
3  i've been unemployed going on three months now...   
4  i ran out of money on my meal card a while bac...   

                             request_text_edit_aware  \
0  I'm not in College, or a starving artist or an...   
1  Hello! It's been a hard 2 months with money an...   
2  I'm sure there are needier people on this subr...   
3  I've been unemployed going on three months now...   
4  I ran out of money on my meal card a while bac...   

                                       request_title  ...  \
0  [Request] Ontario, Canada - On my 3rd of 5 day...  ...   
1   [REQUEST] Southern Arizona, Tucson Hungry Family  ...   
2        [Request] Pizza for a broke college student  ...   
3  [Request] Unemployed and Sick of Rice (Suffolk...  ...   
4  [Request] Ohio USA, broke student musician in ...  ...   

   requester_received_pizza  \
0                      True   
1                      True   
2                      True   
3                      True   
4                      True   

                     requester_subreddits_at_request  \
0  [AdviceAnimals, WTF, funny, gaming, movies, te...   
1                                        [aww, pics]   
2  [AskReddit, DoesAnybodyElse, IAmA, Marijuana, ...   
3  [AdviceAnimals, Art, AskReddit, BookCollecting...   
4                      [TrueAtheism, atheism, funny]   

   requester_upvotes_minus_downvotes_at_request  \
0                                            32   
1                                             5   
2                                          1359   
3                                          1205   
4                                            81   

   requester_upvotes_minus_downvotes_at_retrieval  \
0                                             212   
1                                              21   
2                                            2110   
3                                            4889   
4                                              86   

   requester_upvotes_plus_downvotes_at_request  \
0                                           48   
1                                           13   
2                                         2423   
3                                         2403   
4                                          225   

   requester_upvotes_plus_downvotes_at_retrieval  requester_user_flair  \
0                                            610                shroom   
1                                             57                shroom   


In [7]:
# Split the texts into tokens
df['request_text']= [nltk.word_tokenize(post) for post in df['request_text']]
df.head()

giver_username_if_known  in_test_set  \
0                     N/A        False   
1                     N/A        False   
2                     N/A        False   
3                     N/A        False   
4                     N/A        False   

   number_of_downvotes_of_request_at_retrieval  \
0                                            2   
1                                            2   
2                                            1   
3                                            2   
4                                            1   

   number_of_upvotes_of_request_at_retrieval  post_was_edited request_id  \
0                                          6                0   t3_w5491   
1                                          6                1   t3_qysgy   
2                                          4                1   t3_if0ed   
3                                         13                0   t3_jr3w1   
4                                          4       1366847814  t3_1d18tc   

   request_number_of_comments_at_retrieval  \
0                                        7   
1                                        8   
2                                        1   
3                                        3   
4                                        5   

                                        request_text  \
0  [i, 'm, not, in, college, ,, or, a, starving, ...   
1  [hello, !, it, 's, been, a, hard, 2, months, w...   
2  [i, 'm, sure, there, are, needier, people, on,...   
3  [i, 've, been, unemployed, going, on, three, m...   
4  [i, ran, out, of, money, on, my, meal, card, a...   

                             request_text_edit_aware  \
0  I'm not in College, or a starving artist or an...   
1  Hello! It's been a hard 2 months with money an...   
2  I'm sure there are needier people on this subr...   
3  I've been unemployed going on three months now...   
4  I ran out of money on my meal card a while bac...   

                                       request_title  ...  \
0  [Request] Ontario, Canada - On my 3rd of 5 day...  ...   
1   [REQUEST] Southern Arizona, Tucson Hungry Family  ...   
2        [Request] Pizza for a broke college student  ...   
3  [Request] Unemployed and Sick of Rice (Suffolk...  ...   
4  [Request] Ohio USA, broke student musician in ...  ...   

   requester_received_pizza  \
0                      True   
1                      True   
2                      True   
3                      True   
4                      True   

                     requester_subreddits_at_request  \
0  [AdviceAnimals, WTF, funny, gaming, movies, te...   
1                                        [aww, pics]   
2  [AskReddit, DoesAnybodyElse, IAmA, Marijuana, ...   
3  [AdviceAnimals, Art, AskReddit, BookCollecting...   
4                      [TrueAtheism, atheism, funny]   

   requester_upvotes_minus_downvotes_at_request  \
0                                            32   
1                                             5   
2                                          1359   
3                                          1205   
4                                            81   

   requester_upvotes_minus_downvotes_at_retrieval  \
0                                             212   
1                                              21   
2                                            2110   
3                                            4889   
4                                              86   

   requester_upvotes_plus_downvotes_at_request  \
0                                           48   
1                                           13   
2                                         2423   
3                                         2403   
4                                          225   

   requester_upvotes_plus_downvotes_at_retrieval  requester_user_flair  \
0                                            610                shroom   
1                                             57                shroom   


In [44]:
# Remove Stop words, Non-alphabet and perfom Word Stemming/Lemmenting.


In [8]:
for index,post in enumerate(df['request_text']):
    # Declaring Empty List to store the finalized words which will be the value of a new column 'review_final'
    Final_words = []
    # Initializing WordNetLemmatizer()
    word_Lemmatized = WordNetLemmatizer()
   
    for word in post:
        # Below condition is to check for Stop words and consider only alphabets
        if word not in stopwords.words('english') and word.isalpha():
            word_Final = word_Lemmatized.lemmatize(word)
            Final_words.append(word_Final)
    # The final processed set of words for each iteration will be stored in 'review_final'
    df.loc[index,'review_final'] = str(Final_words)

In [50]:
df.head()

giver_username_if_known  in_test_set  \
0                     N/A        False   
1                     N/A        False   
2                     N/A        False   
3                     N/A        False   
4                     N/A        False   

   number_of_downvotes_of_request_at_retrieval  \
0                                            2   
1                                            2   
2                                            1   
3                                            2   
4                                            1   

   number_of_upvotes_of_request_at_retrieval  post_was_edited request_id  \
0                                          6                0   t3_w5491   
1                                          6                1   t3_qysgy   
2                                          4                1   t3_if0ed   
3                                         13                0   t3_jr3w1   
4                                          4       1366847814  t3_1d18tc   

   request_number_of_comments_at_retrieval  \
0                                        7   
1                                        8   
2                                        1   
3                                        3   
4                                        5   

                                        request_text  \
0  [i, 'm, not, in, college, ,, or, a, starving, ...   
1  [hello, !, it, 's, been, a, hard, 2, months, w...   
2  [i, 'm, sure, there, are, needier, people, on,...   
3  [i, 've, been, unemployed, going, on, three, m...   
4  [i, ran, out, of, money, on, my, meal, card, a...   

                             request_text_edit_aware  \
0  I'm not in College, or a starving artist or an...   
1  Hello! It's been a hard 2 months with money an...   
2  I'm sure there are needier people on this subr...   
3  I've been unemployed going on three months now...   
4  I ran out of money on my meal card a while bac...   

                                       request_title  ...  \
0  [Request] Ontario, Canada - On my 3rd of 5 day...  ...   
1   [REQUEST] Southern Arizona, Tucson Hungry Family  ...   
2        [Request] Pizza for a broke college student  ...   
3  [Request] Unemployed and Sick of Rice (Suffolk...  ...   
4  [Request] Ohio USA, broke student musician in ...  ...   

                     requester_subreddits_at_request  \
0  [AdviceAnimals, WTF, funny, gaming, movies, te...   
1                                        [aww, pics]   
2  [AskReddit, DoesAnybodyElse, IAmA, Marijuana, ...   
3  [AdviceAnimals, Art, AskReddit, BookCollecting...   
4                      [TrueAtheism, atheism, funny]   

   requester_upvotes_minus_downvotes_at_request  \
0                                            32   
1                                             5   
2                                          1359   
3                                          1205   
4                                            81   

   requester_upvotes_minus_downvotes_at_retrieval  \
0                                             212   
1                                              21   
2                                            2110   
3                                            4889   
4                                              86   

   requester_upvotes_plus_downvotes_at_request  \
0                                           48   
1                                           13   
2                                         2423   
3                                         2403   
4                                          225   

   requester_upvotes_plus_downvotes_at_retrieval  requester_user_flair  \
0                                            610                shroom   
1                                             57                shroom   
2                                           3456                shroom   
3                                           8245                shroom   
4                                      

In [9]:
# Encode target label (pizza request succeed or fail)
Encoder = LabelEncoder()
df['requester_received_pizza'] = Encoder.fit_transform(df['requester_received_pizza'])

In [14]:
# Split data into training and testing set
X1_train, X1_test, y1_train, y1_test = model_selection.train_test_split(df['review_final'], df['requester_received_pizza'], test_size=0.1, random_state=42)

In [15]:
from nltk import bigrams
import re

#Join all training posts (the 'review_final' column) to train_words and then used Regex to capture all words across posts
train_words = ' '.join(X1_train)
train_words = re.findall('\'(\w+)\'', train_words)

In [95]:
# Get unigrams
uni = sorted(set(train_words))
# Count the frequency of each unigram in the training posts
uni_count = [(word, train_words.count(word)) for word in uni]
uni_count

[('aa', 1),
 ('aaaaand', 1),
 ('aaaahhh', 1),
 ('aaron', 1),
 ('aback', 1),
 ('abandon', 2),
 ('abandoned', 4),
 ('abate', 1),
 ('abbotsford', 1),
 ('abbreviate', 1),
 ('abc', 2),
 ('abdominal', 2),
 ('aberystwyth', 1),
 ('ability', 15),
 ('able', 475),
 ('ableton', 1),
 ('aboard', 1),
 ('aboot', 1),
 ('abortion', 2),
 ('abot', 1),
 ('abrictosaurus', 2),
 ('abroad', 5),
 ('abruptly', 2),
 ('abscess', 2),
 ('absence', 2),
 ('absolute', 10),
 ('absolutely', 91),
 ('absurd', 1),
 ('abundance', 3),
 ('abundant', 1),
 ('abuse', 5),
 ('abused', 2),
 ('abusive', 1),
 ('ac', 8),
 ('academic', 2),
 ('academically', 1),
 ('acc', 2),
 ('accelerating', 1),
 ('accept', 18),
 ('acceptable', 3),
 ('accepted', 10),
 ('accepting', 1),
 ('accepts', 6),
 ('acces', 1),
 ('access', 26),
 ('accessible', 1),
 ('accident', 39),
 ('accidental', 1),
 ('accidentally', 5),
 ('accommodating', 1),
 ('accommodation', 1),
 ('accompany', 1),
 ('accomplish', 2),
 ('accomplished', 4),
 ('accomplishment', 1),
 ('accordin

In [104]:
# Sort uni_count based on the second element (the counted frequency) of each tuple
uni_count.sort(reverse=True, key = lambda x: x[1])
uni_count
# Get the top 500 unigrams
uni_final = [word[0] for word in uni_count[:500]]
uni_final

['pizza',
 'would',
 'get',
 'help',
 'really',
 'week',
 'food',
 'day',
 'money',
 'could',
 'thanks',
 'pay',
 'work',
 'job',
 'like',
 'time',
 'one',
 'love',
 'last',
 'much',
 'month',
 'someone',
 'got',
 'u',
 'make',
 'anyone',
 'know',
 'back',
 'go',
 'want',
 'forward',
 'right',
 'paid',
 'today',
 'broke',
 'friend',
 'need',
 'next',
 'going',
 'thank',
 'tonight',
 'eat',
 'year',
 'new',
 'anything',
 'something',
 'edit',
 'two',
 'hungry',
 'even',
 'little',
 'night',
 'thing',
 'first',
 'give',
 'http',
 'ca',
 'home',
 'since',
 'account',
 'tomorrow',
 'also',
 'please',
 'guy',
 'able',
 'good',
 'live',
 'pretty',
 'well',
 'way',
 'house',
 'enough',
 'reddit',
 'student',
 'long',
 'family',
 'kind',
 'come',
 'left',
 'bill',
 'appreciate',
 'friday',
 'people',
 'getting',
 'college',
 'story',
 'feel',
 'rent',
 'buy',
 'ramen',
 'hour',
 'use',
 'hey',
 'sure',
 'say',
 'willing',
 'car',
 'still',
 'dinner',
 'bank',
 'nothing',
 'place',
 'nice',
 'a

In [122]:
# Construct a list that contains all of the bigrams across tranining posts
train_words_bi = []
# Get bigrams post by post
for l in X1_train:
    l_words = re.findall('\'(\w+)\'', l)
    l_bi = bigrams(l_words)
    train_words_bi.append(l_bi)
# Flatten the list
train_words_bi = [bi_words for l in train_words_bi for bi_words in l]
train_words_bi    

[('hey', 'would'),
 ('would', 'grateful'),
 ('grateful', 'pizza'),
 ('pizza', 'right'),
 ('right', 'food'),
 ('food', 'moment'),
 ('moment', 'even'),
 ('even', 'ramen'),
 ('ramen', 'left'),
 ('left', 'pay'),
 ('pay', 'check'),
 ('check', 'coming'),
 ('coming', 'till'),
 ('till', 'wednesday'),
 ('wednesday', 'due'),
 ('due', 'labor'),
 ('labor', 'day'),
 ('day', 'weekend'),
 ('weekend', 'test'),
 ('test', 'studying'),
 ('studying', 'right'),
 ('right', 'rochester'),
 ('rochester', 'ny'),
 ('embarrassed', 'ask'),
 ('ask', 'always'),
 ('always', 'giver'),
 ('giver', 'would'),
 ('would', 'love'),
 ('love', 'receive'),
 ('receive', 'large'),
 ('large', 'meat'),
 ('meat', 'lover'),
 ('lover', 'deep'),
 ('deep', 'dish'),
 ('dish', 'pizza'),
 ('pizza', 'cottage'),
 ('cottage', 'inn'),
 ('inn', 'mushroom'),
 ('mushroom', 'onion'),
 ('onion', 'whole'),
 ('whole', 'thing'),
 ('thing', 'jalapeno'),
 ('jalapeno', 'half'),
 ('half', 'boyfriend'),
 ('boyfriend', 'craving'),
 ('craving', 'pizza'),
 ('

In [126]:
print(len(train_words))
print(len(train_words_bi))

187606
182651


In [129]:
# Get unique bigrams
bi = sorted(set(train_words_bi))
# Count the frequency of each bigram in the training posts
bi_count = [(words, train_words_bi.count(words)) for words in bi]
bi_count

[(('aa', 'le'), 1),
 (('aaaaand', 'pay'), 1),
 (('aaaahhh', 'random'), 1),
 (('aback', 'kindness'), 1),
 (('abandon', 'currently'), 1),
 (('abandon', 'got'), 1),
 (('abandoned', 'anything'), 1),
 (('abandoned', 'dog'), 1),
 (('abandoned', 'family'), 1),
 (('abandoned', 'girlfriend'), 1),
 (('abate', 'munchies'), 1),
 (('abbotsford', 'bc'), 1),
 (('abbreviate', 'know'), 1),
 (('abc', 'news'), 1),
 (('abc', 'think'), 1),
 (('abdominal', 'hysterectomy'), 1),
 (('abdominal', 'pain'), 1),
 (('aberystwyth', 'several'), 1),
 (('ability', 'celebrate'), 1),
 (('ability', 'eat'), 1),
 (('ability', 'even'), 1),
 (('ability', 'frequently'), 1),
 (('ability', 'get'), 1),
 (('ability', 'learn'), 1),
 (('ability', 'm'), 1),
 (('ability', 'make'), 1),
 (('ability', 'order'), 1),
 (('ability', 'pizza'), 1),
 (('ability', 'pretty'), 1),
 (('ability', 'provided'), 1),
 (('ability', 'reddit'), 1),
 (('ability', 'whatsoever'), 1),
 (('able', 'able'), 1),
 (('able', 'access'), 1),
 (('able', 'actually'), 1)

In [138]:
# Sort bi_count based on the second element (the counted frequency) of each tuple
bi_count.sort(reverse=True, key = lambda x: x[1])
bi_count
# Get the top 500 unigrams
bi_final = [words[0] for words in bi_count[:500]]
bi_final = [words[0] + ' ' + words[1] for words in bi_final]
bi_final

['pizza would',
 'pay forward',
 'get paid',
 'would love',
 'would really',
 'love pizza',
 'next week',
 'could help',
 'bank account',
 'would like',
 'college student',
 'help would',
 'pizza hut',
 'get pizza',
 'really appreciate',
 'sob story',
 'help u',
 'return favor',
 'year old',
 'first time',
 'could really',
 'please help',
 'new job',
 'thanks reading',
 'someone could',
 'would greatly',
 'lost job',
 'last night',
 'pretty much',
 'last week',
 'thanks advance',
 'papa john',
 'feel like',
 'two week',
 'anyone could',
 'pizza tonight',
 'really use',
 'send pizza',
 'could use',
 'anyone help',
 'someone else',
 'random act',
 'would make',
 'food stamp',
 'week ago',
 'pay back',
 'use pizza',
 'willing help',
 'greatly appreciated',
 'would nice',
 'buy pizza',
 'couple day',
 'act pizza',
 'ca afford',
 'get back',
 'someone would',
 'u pizza',
 'would awesome',
 'appreciate pizza',
 'month ago',
 'craving pizza',
 'would appreciate',
 'like pizza',
 'thank much',

In [112]:
# Fit the top 500 unigrams to the CountVectorizer
vect = CountVectorizer().fit(uni_final)
vect.get_feature_names()

['able',
 'absolutely',
 'account',
 'act',
 'actually',
 'advance',
 'afford',
 'ago',
 'almost',
 'alone',
 'already',
 'also',
 'always',
 'amazing',
 'amp',
 'another',
 'anyone',
 'anything',
 'anyway',
 'apartment',
 'appreciate',
 'appreciated',
 'area',
 'around',
 'ask',
 'asked',
 'asking',
 'ate',
 'away',
 'awesome',
 'baby',
 'back',
 'bad',
 'bank',
 'barely',
 'basically',
 'bean',
 'believe',
 'best',
 'better',
 'big',
 'bill',
 'birthday',
 'bit',
 'bought',
 'boy',
 'boyfriend',
 'bread',
 'break',
 'broke',
 'brother',
 'buck',
 'budget',
 'buy',
 'ca',
 'call',
 'came',
 'car',
 'card',
 'care',
 'cash',
 'cat',
 'celebrate',
 'change',
 'check',
 'cheer',
 'cheese',
 'child',
 'city',
 'class',
 'close',
 'code',
 'college',
 'come',
 'coming',
 'community',
 'company',
 'completely',
 'cook',
 'cooking',
 'cool',
 'could',
 'couple',
 'course',
 'craving',
 'credit',
 'currently',
 'cut',
 'dad',
 'daughter',
 'day',
 'deal',
 'decided',
 'definitely',
 'deliciou

In [143]:
# Fit the top 500 bigrams to the CountVectorizer
vect2 = CountVectorizer(analyzer='word', ngram_range=(2, 2)).fit(bi_final)
vect2.get_feature_names()

['able afford',
 'able eat',
 'able find',
 'able get',
 'able give',
 'able help',
 'able pay',
 'act pizza',
 'amp amp',
 'another week',
 'anyone could',
 'anyone feel',
 'anyone feeling',
 'anyone help',
 'anyone kind',
 'anyone want',
 'anyone willing',
 'anyone would',
 'anything eat',
 'anything else',
 'anything would',
 'appreciate help',
 'appreciate pizza',
 'appreciated thanks',
 'ask help',
 'asking help',
 'asking pizza',
 'back foot',
 'back home',
 'back school',
 'back work',
 'bank account',
 'best friend',
 'brighten day',
 'broke college',
 'broke hungry',
 'buy food',
 'buy one',
 'buy pizza',
 'buy someone',
 'ca afford',
 'ca even',
 'ca get',
 'ca really',
 'car broke',
 'checking account',
 'cheese pizza',
 'cheesy goodness',
 'college kid',
 'college student',
 'come back',
 'comfort food',
 'completely broke',
 'could afford',
 'could get',
 'could give',
 'could go',
 'could help',
 'could make',
 'could really',
 'could send',
 'could use',
 'couple day',
 

In [156]:
# Transform the training and test data to a matrix respectively for post vectorization based on unigrams
X1_uni_train_vectorized = vect.transform(X1_train)
X1_uni_test_vectorized = vect.transform(X1_test)

print(X1_uni_train_vectorized.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [157]:
# Transform the training and test data to a matrix respectively for post vectorization based on bigrams
X1_bi_train_vectorized = vect2.transform(X1_train)
X1_bi_test_vectorized = vect2.transform(X1_test)

print(X1_bi_train_vectorized.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [160]:
# Join the unigrams matrix and bigrams matrix to a matrix (n*1000 dimensions) 
import scipy.sparse as sp
X1_train_vectorized = sp.hstack((X1_uni_train_vectorized, X1_bi_train_vectorized), format='csr')
X1_test_vectorized = sp.hstack((X1_uni_test_vectorized, X1_bi_test_vectorized), format='csr')

In [262]:
# Classifier - Algorithm - SVM
# fit the training dataset on the classifier
SVM1 = svm.SVC(C=1.0, kernel='linear', class_weight = 'balanced')
SVM1.fit(X1_train_vectorized, y1_train)
# predict the labels on validation dataset
predictions_SVM1 = SVM1.predict(X1_test_vectorized)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(y1_test, predictions_SVM1)*100)

SVM Accuracy Score ->  61.443661971830984


In [263]:
#from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve, auc, confusion_matrix
print('Accuracy Score: ', accuracy_score(y1_test, predictions_SVM1))
print('Precision Score: ', precision_score(y1_test, predictions_SVM1))
print('Recall Score: ', recall_score(y1_test, predictions_SVM1))
print('F1 Score: ', f1_score(y1_test, predictions_SVM1))
#print('AUC Score: ', metrics.roc_auc_score(y1_test, predictions_SVM1))
fpr, tpr, thresholds = roc_curve(y1_test, predictions_SVM1)
print('AUC Score: ', auc(fpr, tpr))
tn, fp, fn, tp = confusion_matrix(y1_test, predictions_SVM1).ravel()
print('Specificity: ', tn / (tn+fp))

Accuracy Score:  0.6144366197183099
Precision Score:  0.31958762886597936
Recall Score:  0.4161073825503356
F1 Score:  0.36151603498542273
AUC Score:  0.5505357915138313
Specificity:  0.684964200477327


# Model 2 – Activity and Reputation

In [136]:
# Model 2 – Activity and Reputation


df['post_was_edited'] = Encoder.fit_transform(df['post_was_edited'])

# Split data into training and testing set
X2_1_train, X2_1_test, y2_train, y2_test = model_selection.train_test_split(df['requester_subreddits_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
#X2_2_train, X2_2_test, y2_train, y2_test = model_selection.train_test_split(df['requester_user_flair'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_3_train, X2_3_test, y2_train, y2_test = model_selection.train_test_split(df['post_was_edited'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_4_train, X2_4_test, y2_train, y2_test = model_selection.train_test_split(df['number_of_downvotes_of_request_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_5_train, X2_5_test, y2_train, y2_test = model_selection.train_test_split(df['number_of_upvotes_of_request_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_6_train, X2_6_test, y2_train, y2_test = model_selection.train_test_split(df['requester_upvotes_plus_downvotes_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_7_train, X2_7_test, y2_train, y2_test = model_selection.train_test_split(df['requester_account_age_in_days_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_8_train, X2_8_test, y2_train, y2_test = model_selection.train_test_split(df['requester_account_age_in_days_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_9_train, X2_9_test, y2_train, y2_test = model_selection.train_test_split(df['requester_days_since_first_post_on_raop_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_10_train, X2_10_test, y2_train, y2_test = model_selection.train_test_split(df['requester_days_since_first_post_on_raop_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_11_train, X2_11_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_comments_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_12_train, X2_12_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_comments_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_13_train, X2_13_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_comments_in_raop_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_14_train, X2_14_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_comments_in_raop_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_15_train, X2_15_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_posts_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_16_train, X2_16_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_posts_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_17_train, X2_17_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_posts_on_raop_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_18_train, X2_18_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_posts_on_raop_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_19_train, X2_19_test, y2_train, y2_test = model_selection.train_test_split(df['requester_number_of_subreddits_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_20_train, X2_20_test, y2_train, y2_test = model_selection.train_test_split(df['requester_upvotes_minus_downvotes_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_21_train, X2_21_test, y2_train, y2_test = model_selection.train_test_split(df['requester_upvotes_minus_downvotes_at_retrieval'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X2_22_train, X2_22_test, y2_train, y2_test = model_selection.train_test_split(df['requester_upvotes_plus_downvotes_at_request'], df['requester_received_pizza'], test_size=0.1, random_state=42)


y2_test == y1_test

3671    True
5183    True
1859    True
2589    True
1662    True
        ... 
151     True
763     True
3724    True
2464    True
4023    True
Name: requester_received_pizza, Length: 568, dtype: bool

In [137]:
# Use unigram to vectorize 'requester_subreddits_at_request'

# Constrcut a list that contains the string of each post's 'requester_subreddits_at_request'
X2_1_train = [str(l) for l in X2_1_train]
X2_1_test = [str(l) for l in X2_1_test]

# Convert all subreddits from training posts to feature names
vect_subr_uni = CountVectorizer().fit(X2_1_train)
vect_subr_uni.get_feature_names()



['0x10c',
 '0x10cships',
 '1000words',
 '100movies365days',
 '100pushups',
 '100sets',
 '1200isplenty',
 '1337',
 '1558',
 '1776',
 '1780',
 '1800s',
 '1911',
 '1920s',
 '1930s',
 '1942',
 '195',
 '1960s',
 '1970s',
 '1980s',
 '1984',
 '1985',
 '1985sweet1985',
 '1990s',
 '1990scartoons',
 '2000s',
 '2006scape',
 '2007scape',
 '200situps',
 '2011',
 '2012elections',
 '2013',
 '2015',
 '2021',
 '2022',
 '2112',
 '240sx',
 '247survival',
 '24hoursupport',
 '250r',
 '2999',
 '29er',
 '2brokegirls',
 '2gointr',
 '2x_intj',
 '2xlite',
 '2xlookbook',
 '2xpdx',
 '2xredditmeet',
 '3000',
 '300zx',
 '30daysit',
 '30rock',
 '311',
 '321',
 '32bites',
 '3amjokes',
 '3d6',
 '3dmodeling',
 '3dprinting',
 '3ds',
 '3dsfcswap',
 '3dsmax',
 '3dspics',
 '400bc',
 '42000',
 '45thworldproblems',
 '49ers',
 '4chan',
 '4hourbodyslowcarb',
 '4sentencemoviereviews',
 '4wordalbumreviews',
 '4x4',
 '50hz',
 '50shadesofgreen',
 '52weeksofcooking',
 '52weeksofdesign',
 '54thworldproblems',
 '734',
 '80scartoons',

In [138]:
# Transform the training and test data to a matrix respectively for 'requester_subreddits_at_request' vectorization based on subreddits
X2_subr_train_vectorized = vect_subr_uni.transform(X2_1_train)
X2_subr_test_vectorized = vect_subr_uni.transform(X2_1_test)

#print(X2_subr_train_vectorized.toarray())

In [139]:
# Convert data frames to matrices
X2_3_train_vectorized = sp.csr_matrix(X2_3_train).transpose()
X2_4_train_vectorized = sp.csr_matrix(X2_4_train).transpose()
X2_5_train_vectorized = sp.csr_matrix(X2_5_train).transpose()
X2_6_train_vectorized = sp.csr_matrix(X2_6_train).transpose()
X2_7_train_vectorized = sp.csr_matrix(X2_7_train).transpose()
X2_8_train_vectorized = sp.csr_matrix(X2_8_train).transpose()
X2_9_train_vectorized = sp.csr_matrix(X2_9_train).transpose()
X2_10_train_vectorized = sp.csr_matrix(X2_10_train).transpose()
X2_11_train_vectorized = sp.csr_matrix(X2_11_train).transpose()
X2_12_train_vectorized = sp.csr_matrix(X2_12_train).transpose()
X2_13_train_vectorized = sp.csr_matrix(X2_13_train).transpose()
X2_14_train_vectorized = sp.csr_matrix(X2_14_train).transpose()
X2_15_train_vectorized = sp.csr_matrix(X2_15_train).transpose()
X2_16_train_vectorized = sp.csr_matrix(X2_16_train).transpose()
X2_17_train_vectorized = sp.csr_matrix(X2_17_train).transpose()
X2_18_train_vectorized = sp.csr_matrix(X2_18_train).transpose()
X2_19_train_vectorized = sp.csr_matrix(X2_19_train).transpose()
X2_20_train_vectorized = sp.csr_matrix(X2_20_train).transpose()
X2_21_train_vectorized = sp.csr_matrix(X2_21_train).transpose()
X2_22_train_vectorized = sp.csr_matrix(X2_22_train).transpose()

X2_3_test_vectorized = sp.csr_matrix(X2_3_test).transpose()
X2_4_test_vectorized = sp.csr_matrix(X2_4_test).transpose()
X2_5_test_vectorized = sp.csr_matrix(X2_5_test).transpose()
X2_6_test_vectorized = sp.csr_matrix(X2_6_test).transpose()
X2_7_test_vectorized = sp.csr_matrix(X2_7_test).transpose()
X2_8_test_vectorized = sp.csr_matrix(X2_8_test).transpose()
X2_9_test_vectorized = sp.csr_matrix(X2_9_test).transpose()
X2_10_test_vectorized = sp.csr_matrix(X2_10_test).transpose()
X2_11_test_vectorized = sp.csr_matrix(X2_11_test).transpose()
X2_12_test_vectorized = sp.csr_matrix(X2_12_test).transpose()
X2_13_test_vectorized = sp.csr_matrix(X2_13_test).transpose()
X2_14_test_vectorized = sp.csr_matrix(X2_14_test).transpose()
X2_15_test_vectorized = sp.csr_matrix(X2_15_test).transpose()
X2_16_test_vectorized = sp.csr_matrix(X2_16_test).transpose()
X2_17_test_vectorized = sp.csr_matrix(X2_17_test).transpose()
X2_18_test_vectorized = sp.csr_matrix(X2_18_test).transpose()
X2_19_test_vectorized = sp.csr_matrix(X2_19_test).transpose()
X2_20_test_vectorized = sp.csr_matrix(X2_20_test).transpose()
X2_21_test_vectorized = sp.csr_matrix(X2_21_test).transpose()
X2_22_test_vectorized = sp.csr_matrix(X2_22_test).transpose()

# Join each matrix to a single matrix
X2_train_vectorized = sp.hstack((X2_subr_train_vectorized, X2_3_train_vectorized, X2_4_train_vectorized, X2_5_train_vectorized, X2_6_train_vectorized, X2_7_train_vectorized, X2_8_train_vectorized, X2_9_train_vectorized, X2_10_train_vectorized, X2_11_train_vectorized, X2_12_train_vectorized, X2_13_train_vectorized, X2_14_train_vectorized, X2_15_train_vectorized, X2_16_train_vectorized, X2_17_train_vectorized, X2_18_train_vectorized, X2_19_train_vectorized, X2_20_train_vectorized, X2_21_train_vectorized, X2_22_train_vectorized), format='csr')
X2_test_vectorized = sp.hstack((X2_subr_test_vectorized, X2_3_test_vectorized, X2_4_test_vectorized, X2_5_test_vectorized, X2_6_test_vectorized, X2_7_test_vectorized, X2_8_test_vectorized, X2_9_test_vectorized, X2_10_test_vectorized, X2_11_test_vectorized, X2_12_test_vectorized, X2_13_test_vectorized, X2_14_test_vectorized, X2_15_test_vectorized, X2_16_test_vectorized, X2_17_test_vectorized, X2_18_test_vectorized, X2_19_test_vectorized, X2_20_test_vectorized, X2_21_test_vectorized, X2_22_test_vectorized), format='csr')
print(X2_train_vectorized.toarray())

[[   0.    0.    0. ... 2565. 2826. 3807.]
 [   0.    0.    0. ...  237. 4965.  423.]
 [   0.    0.    0. ...  201.  202.  269.]
 ...
 [   0.    0.    0. ...  911. 4710. 1959.]
 [   0.    0.    0. ...    6.   11.    8.]
 [   0.    0.    0. ...   78.  378.  128.]]


In [140]:
# Classifier - Algorithm - SVM
# fit the training dataset on the classifier
SVM2 = svm.SVC(C=1.0, kernel='linear', class_weight = 'balanced')
SVM2.fit(X2_train_vectorized, y2_train)
# predict the labels on validation dataset
predictions_SVM2 = SVM2.predict(X2_test_vectorized)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(y2_test, predictions_SVM2)*100)

SVM Accuracy Score ->  65.84507042253522


In [141]:
#from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve, auc, confusion_matrix
print('Accuracy Score: ', accuracy_score(y2_test, predictions_SVM2))
print('Precision Score: ', precision_score(y2_test, predictions_SVM2))
print('Recall Score: ', recall_score(y2_test, predictions_SVM2))
print('F1 Score: ', f1_score(y2_test, predictions_SVM2))
#print('AUC Score: ', metrics.roc_auc_score(y2_test, predictions_SVM))
fpr, tpr, thresholds = roc_curve(y2_test, predictions_SVM2)
print('AUC Score: ', auc(fpr, tpr))
tn, fp, fn, tp = confusion_matrix(y2_test, predictions_SVM2).ravel()
print('Specificity: ', tn / (tn+fp))

Accuracy Score:  0.6584507042253521
Precision Score:  0.4157303370786517
Recall Score:  0.7449664429530202
F1 Score:  0.5336538461538461
AUC Score:  0.6863257035767487
Specificity:  0.6276849642004774


# Model 3 – Narratives

In [26]:
# Model 3 – Narratives

# Use join to get the regex expression for narrative_desire, family, job, money, and student
fhand_desire = open('narratives/desire.txt')
text_desire = fhand_desire.read()
rg_desire = '|'.join(text_desire.split('\n'))

print(rg_desire)

fhand_family = open('narratives/family.txt')
text_family= fhand_family.read()
rg_family = '|'.join(text_family.split('\n'))

fhand_job = open('narratives/job.txt')
text_job= fhand_job.read()
rg_job = '|'.join(text_job.split('\n'))

fhand_money = open('narratives/money.txt')
text_money= fhand_money.read()
rg_money = '|'.join(text_money.split('\n'))

fhand_student = open('narratives/student.txt')
text_student= fhand_student.read()
rg_student = '|'.join(text_student.split('\n'))

# Perform Regex match. Calculate the ratio of the number of matches for each narrative to the total number of white spaced words in the post, and store in new columns
for index, post in enumerate(df['review_final']):
    total = len(re.findall('\', \'', post)) + 1
    df.loc[index, 'narra_desire'] = len(re.findall(rg_desire, post))/total
    df.loc[index, 'narra_family'] = len(re.findall(rg_family, post))/total
    df.loc[index, 'narra_job'] = len(re.findall(rg_job, post))/total
    df.loc[index, 'narra_money'] = len(re.findall(rg_money, post))/total
    df.loc[index, 'narra_student'] = len(re.findall(rg_student, post))/total

friend|party|birthday|boyfriend|girlfriend|date|drinks|drunk|wasted|invite|invited|celebrate|celebrating|game|games|movie|beer|crave|craving


In [27]:
df.head()

giver_username_if_known  in_test_set  \
0                     N/A        False   
1                     N/A        False   
2                     N/A        False   
3                     N/A        False   
4                     N/A        False   

   number_of_downvotes_of_request_at_retrieval  \
0                                            2   
1                                            2   
2                                            1   
3                                            2   
4                                            1   

   number_of_upvotes_of_request_at_retrieval  post_was_edited request_id  \
0                                          6                0   t3_w5491   
1                                          6                1   t3_qysgy   
2                                          4                1   t3_if0ed   
3                                         13                0   t3_jr3w1   
4                                          4       1366847814  t3_1d18tc   

   request_number_of_comments_at_retrieval  \
0                                        7   
1                                        8   
2                                        1   
3                                        3   
4                                        5   

                                        request_text  \
0  [i, 'm, not, in, college, ,, or, a, starving, ...   
1  [hello, !, it, 's, been, a, hard, 2, months, w...   
2  [i, 'm, sure, there, are, needier, people, on,...   
3  [i, 've, been, unemployed, going, on, three, m...   
4  [i, ran, out, of, money, on, my, meal, card, a...   

                             request_text_edit_aware  \
0  I'm not in College, or a starving artist or an...   
1  Hello! It's been a hard 2 months with money an...   
2  I'm sure there are needier people on this subr...   
3  I've been unemployed going on three months now...   
4  I ran out of money on my meal card a while bac...   

                                       request_title  ...  \
0  [Request] Ontario, Canada - On my 3rd of 5 day...  ...   
1   [REQUEST] Southern Arizona, Tucson Hungry Family  ...   
2        [Request] Pizza for a broke college student  ...   
3  [Request] Unemployed and Sick of Rice (Suffolk...  ...   
4  [Request] Ohio USA, broke student musician in ...  ...   

   requester_user_flair  requester_username  unix_timestamp_of_request  \
0                shroom   RitalinYourMemory                 1341604684   
1                shroom          blubirdhvn                 1331868375   
2                shroom            taterpot                 1309622289   
3                shroom        or_me_bender                 1314060079   
4                shroom        m_chamberlin                 1366839643   

   unix_timestamp_of_request_utc  \
0                     1341601084   
1                     1331864775   
2                     1309618689   
3                     1314056479   
4                     1366836043   

                                        review_final  narra_desire  \
0  ['college', 'starving', 'artist', 'anything', ...      0.000000   
1  ['hello', 'hard', 'month', 'money', 'listed', ...      0.000000   
2  ['sure', 'needier', 'people', 'subreddit', 'bo...      0.000000   
3  ['unemployed', 'going', 'three', 'month', 'unf...      0.052632   
4  ['ran', 'money', 'meal', 'card', 'back', 'fini...      0.000000   

   narra_family  narra_job  narra_money  narra_student  
0      0.000000   0.043478     0.159420       0.014493  
1      0.071429   0.000000     0.166667       0.000000  
2      0.000000   0.000000     0.139535       0.000000  
3      0.000000   0.052632     0.105263       0.052632  
4      0.024390   0.000000     0.121951       0.000000  

[5 rows x 39 columns]

In [28]:
# Split data into training and testing set
X3_1_train, X3_1_test, y3_train, y3_test = model_selection.train_test_split(df['narra_desire'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X3_2_train, X3_2_test, y3_train, y3_test = model_selection.train_test_split(df['narra_family'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X3_3_train, X3_3_test, y3_train, y3_test = model_selection.train_test_split(df['narra_job'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X3_4_train, X3_4_test, y3_train, y3_test = model_selection.train_test_split(df['narra_money'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X3_5_train, X3_5_test, y3_train, y3_test = model_selection.train_test_split(df['narra_student'], df['requester_received_pizza'], test_size=0.1, random_state=42)

In [29]:
# Convert data frames to matrices
X3_1_train_vectorized = sp.csr_matrix(X3_1_train).transpose()
X3_2_train_vectorized = sp.csr_matrix(X3_2_train).transpose()
X3_3_train_vectorized = sp.csr_matrix(X3_3_train).transpose()
X3_4_train_vectorized = sp.csr_matrix(X3_4_train).transpose()
X3_5_train_vectorized = sp.csr_matrix(X3_5_train).transpose()

X3_1_test_vectorized = sp.csr_matrix(X3_1_test).transpose()
X3_2_test_vectorized = sp.csr_matrix(X3_2_test).transpose()
X3_3_test_vectorized = sp.csr_matrix(X3_3_test).transpose()
X3_4_test_vectorized = sp.csr_matrix(X3_4_test).transpose()
X3_5_test_vectorized = sp.csr_matrix(X3_5_test).transpose()

# Join each matrix to a single matrix
X3_train_vectorized = sp.hstack((X3_1_train_vectorized, X3_2_train_vectorized, X3_3_train_vectorized, X3_4_train_vectorized, X3_5_train_vectorized), format='csr')
X3_test_vectorized = sp.hstack((X3_1_test_vectorized, X3_2_test_vectorized, X3_3_test_vectorized, X3_4_test_vectorized, X3_5_test_vectorized), format='csr')

print(X3_train_vectorized.toarray())

[[0.         0.04166667 0.         0.25       0.04166667]
 [0.02985075 0.         0.         0.14925373 0.02985075]
 [0.         0.         0.02083333 0.0625     0.        ]
 ...
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.10526316 0.        ]]


In [30]:
# Classifier - Algorithm - SVM
# fit the training dataset on the classifier
SVM3 = svm.SVC(C=1.0, kernel='linear', class_weight = 'balanced')
SVM3.fit(X3_train_vectorized, y3_train)
# predict the labels on validation dataset
predictions_SVM3 = SVM3.predict(X3_test_vectorized)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(y3_test, predictions_SVM3)*100)

SVM Accuracy Score ->  60.91549295774647


In [31]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve, auc, confusion_matrix
print('Accuracy Score: ', accuracy_score(y3_test, predictions_SVM3))
print('Precision Score: ', precision_score(y3_test, predictions_SVM3))
print('Recall Score: ', recall_score(y3_test, predictions_SVM3))
print('F1 Score: ', f1_score(y3_test, predictions_SVM3))
fpr, tpr, thresholds = roc_curve(y3_test, predictions_SVM3)
print('AUC Score: ', auc(fpr, tpr))
tn, fp, fn, tp = confusion_matrix(y3_test, predictions_SVM3).ravel()
print('Specificity: ', tn / (tn+fp))

Accuracy Score:  0.6091549295774648
Precision Score:  0.3253588516746411
Recall Score:  0.4563758389261745
F1 Score:  0.3798882681564246
AUC Score:  0.5599301628998414
Specificity:  0.6634844868735084


In [17]:
import scipy.sparse as sp
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

# Model 4 – Moral foundations

In [32]:
# Model 4 – Moral foundations

# Construct a list that contains each line of the moral dict. Use strip() to remove the white spaces at the beginning and end of line
fhand_moral = open('MoralFoundations.dic')
moral_dict = [row.strip() for row in fhand_moral]
moral_dict

['%',
 '01                    HarmVirtue',
 '02                    HarmVice',
 '03                    FairnessVirtue',
 '04                    FairnessVice',
 '05                    IngroupVirtue',
 '06                    IngroupVice',
 '07                    AuthorityVirtue',
 '08                    AuthorityVice',
 '09                    PurityVirtue',
 '10                    PurityVice',
 '11                    MoralityGeneral',
 '%',
 '',
 'safe*\t\t\t01',
 'peace*\t\t\t01',
 'compassion*\t\t01',
 'empath*\t\t\t01',
 'sympath*\t\t01',
 'care\t\t\t01',
 'caring\t\t\t01',
 'protect*\t\t01',
 'shield\t\t\t01',
 'shelter\t\t\t01',
 'amity\t\t\t01',
 'secur*\t\t\t01',
 'benefit*        \t01',
 'defen*\t\t\t01',
 'guard*\t\t\t01',
 'preserve\t\t01 07 09',
 '',
 'harm*\t\t\t02',
 'suffer*\t\t\t02',
 'war\t\t\t02',
 'wars\t\t\t02',
 'warl*\t\t\t02',
 'warring\t\t\t02',
 'fight*\t\t\t02',
 'violen*\t\t\t02',
 'hurt*\t\t\t02',
 'kill\t\t\t02',
 'kills\t\t\t02',
 'killer*\t\t\t02',
 'killed\t

In [33]:
# Calculate where (which line) does the dict actually start
i = 0
for line in moral_dict:
    if line.startswith('safe'):
        print(i)
        break
    i = i+1  

14


In [34]:
# Slicing the dict to only contain words without index
moral_dict = moral_dict[i:]
moral_dict

['safe*\t\t\t01',
 'peace*\t\t\t01',
 'compassion*\t\t01',
 'empath*\t\t\t01',
 'sympath*\t\t01',
 'care\t\t\t01',
 'caring\t\t\t01',
 'protect*\t\t01',
 'shield\t\t\t01',
 'shelter\t\t\t01',
 'amity\t\t\t01',
 'secur*\t\t\t01',
 'benefit*        \t01',
 'defen*\t\t\t01',
 'guard*\t\t\t01',
 'preserve\t\t01 07 09',
 '',
 'harm*\t\t\t02',
 'suffer*\t\t\t02',
 'war\t\t\t02',
 'wars\t\t\t02',
 'warl*\t\t\t02',
 'warring\t\t\t02',
 'fight*\t\t\t02',
 'violen*\t\t\t02',
 'hurt*\t\t\t02',
 'kill\t\t\t02',
 'kills\t\t\t02',
 'killer*\t\t\t02',
 'killed\t\t\t02',
 'killing\t\t\t02',
 'endanger*\t\t02',
 'cruel*\t\t\t02',
 'brutal*\t\t\t02',
 'abuse*\t\t\t02',
 'damag*\t\t\t02',
 'ruin*\t\t\t02 10',
 'ravage\t\t\t02',
 'detriment*\t\t02',
 'crush*\t\t\t02',
 'attack*\t\t\t02',
 'annihilate*\t\t02',
 'destroy\t\t\t02',
 'stomp\t\t\t02',
 'abandon*\t\t02 06',
 'spurn\t\t\t02',
 'impair\t\t\t02',
 'exploit\t\t\t02 10',
 'exploits\t\t02 10',
 'exploited\t\t02 10',
 'exploiting\t\t02 10',
 'wound*\t

In [35]:
# Construct vocabulary lists for each moral foundation dimension
HarmVirtue_dict = []
HarmVice_dict = []
IngroupVirtue_dict = []
IngroupVice_dict = []
AuthorityVirtue_dict = []
AuthorityVice_dict = []
PurityVirtue_dict = []
PurityVice_dict = []

In [36]:
for line in moral_dict:
    if re.search('01', line):  
        HarmVirtue_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*01', line)[0])
    if re.search('02', line):  
        HarmVice_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*02', line)[0])
    if re.search('05', line):  
        IngroupVirtue_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*05', line)[0])   
    if re.search('06', line):  
        IngroupVice_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*06', line)[0])   
    if re.search('07', line):  
        AuthorityVirtue_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*07', line)[0])   
    if re.search('08', line):  
        AuthorityVice_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*08', line)[0])   
    if re.search('09', line):  
        PurityVirtue_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*09', line)[0])   
    if re.search('10', line):  
        PurityVice_dict.append(re.findall('([a-z]+)\*?\s+(?:\d* )*10', line)[0])   

print(PurityVice_dict)

['ruin', 'exploit', 'exploits', 'exploited', 'exploiting', 'apostasy', 'apostate', 'heretic', 'disgust', 'deprav', 'disease', 'unclean', 'contagio', 'indecen', 'sin', 'sinful', 'sinner', 'sins', 'sinned', 'sinning', 'slut', 'whore', 'dirt', 'impiety', 'impious', 'profan', 'gross', 'repuls', 'sick', 'promiscu', 'lewd', 'adulter', 'debauche', 'defile', 'tramp', 'prostitut', 'unchaste', 'intemperate', 'wanton', 'profligate', 'filth', 'trashy', 'obscen', 'lax', 'taint', 'stain', 'tarnish', 'debase', 'desecrat', 'wicked', 'blemish', 'exploitat', 'pervert', 'wretched']


In [119]:
# Use join to get the regex expression for each moral foundation dimension
rg_HarmVirtue = '|'.join(HarmVirtue_dict)
rg_HarmVice = '|'.join(HarmVice_dict)
rg_IngroupVirtue = '|'.join(IngroupVirtue_dict)
rg_IngroupVice = '|'.join(IngroupVice_dict)
rg_AuthorityVirtue = '|'.join(AuthorityVirtue_dict)
rg_AuthorityVice = '|'.join(AuthorityVice_dict)
rg_PurityVirtue = '|'.join(PurityVirtue_dict)
rg_PurityVice = '|'.join(PurityVice_dict)

rg_PurityVice

'ruin|exploit|exploits|exploited|exploiting|apostasy|apostate|heretic|disgust|deprav|disease|unclean|contagio|indecen|sin|sinful|sinner|sins|sinned|sinning|slut|whore|dirt|impiety|impious|profan|gross|repuls|sick|promiscu|lewd|adulter|debauche|defile|tramp|prostitut|unchaste|intemperate|wanton|profligate|filth|trashy|obscen|lax|taint|stain|tarnish|debase|desecrat|wicked|blemish|exploitat|pervert|wretched'

In [121]:
# Perform Regex match. Calculate the ratio of the number of matches for each moral foundation to the total number of white spaced words in the post, and store in new columns
for index, post in enumerate(df['review_final']):
    total = len(re.findall('\', \'', post)) + 1
    df.loc[index, 'moral_harm+'] = len(re.findall(rg_HarmVirtue, post))/total
    df.loc[index, 'moral_harm-'] = len(re.findall(rg_HarmVice, post))/total
    df.loc[index, 'moral_ingroup+'] = len(re.findall(rg_IngroupVirtue, post))/total
    df.loc[index, 'moral_ingroup-'] = len(re.findall(rg_IngroupVice, post))/total
    df.loc[index, 'moral_authority+'] = len(re.findall(rg_AuthorityVirtue, post))/total
    df.loc[index, 'moral_authority-'] = len(re.findall(rg_AuthorityVice, post))/total
    df.loc[index, 'moral_purity+'] = len(re.findall(rg_PurityVirtue, post))/total
    df.loc[index, 'moral_purity-'] = len(re.findall(rg_PurityVice, post))/total

In [122]:
df.head()

giver_username_if_known  in_test_set  \
0                     N/A        False   
1                     N/A        False   
2                     N/A        False   
3                     N/A        False   
4                     N/A        False   

   number_of_downvotes_of_request_at_retrieval  \
0                                            2   
1                                            2   
2                                            1   
3                                            2   
4                                            1   

   number_of_upvotes_of_request_at_retrieval  post_was_edited request_id  \
0                                          6                0   t3_w5491   
1                                          6                1   t3_qysgy   
2                                          4                1   t3_if0ed   
3                                         13                0   t3_jr3w1   
4                                          4       1366847814  t3_1d18tc   

   request_number_of_comments_at_retrieval  \
0                                        7   
1                                        8   
2                                        1   
3                                        3   
4                                        5   

                                        request_text  \
0  [i, 'm, not, in, college, ,, or, a, starving, ...   
1  [hello, !, it, 's, been, a, hard, 2, months, w...   
2  [i, 'm, sure, there, are, needier, people, on,...   
3  [i, 've, been, unemployed, going, on, three, m...   
4  [i, ran, out, of, money, on, my, meal, card, a...   

                             request_text_edit_aware  \
0  I'm not in College, or a starving artist or an...   
1  Hello! It's been a hard 2 months with money an...   
2  I'm sure there are needier people on this subr...   
3  I've been unemployed going on three months now...   
4  I ran out of money on my meal card a while bac...   

                                       request_title  ...  narra_money  \
0  [Request] Ontario, Canada - On my 3rd of 5 day...  ...     0.159420   
1   [REQUEST] Southern Arizona, Tucson Hungry Family  ...     0.166667   
2        [Request] Pizza for a broke college student  ...     0.139535   
3  [Request] Unemployed and Sick of Rice (Suffolk...  ...     0.105263   
4  [Request] Ohio USA, broke student musician in ...  ...     0.121951   

   narra_student  moral_harm+  moral_harm-  moral_ingroup+  moral_ingroup-  \
0       0.014493          0.0     0.014493        0.043478             0.0   
1       0.000000          0.0     0.000000        0.071429             0.0   
2       0.000000          0.0     0.000000        0.000000             0.0   
3       0.052632          0.0     0.052632        0.000000             0.0   
4       0.000000          0.0     0.000000        0.024390             0.0   

   moral_authority+  moral_authority-  moral_purity+  moral_purity-  
0               0.0               0.0            0.0       0.014493  
1               0.0               0.0            0.0       0.000000  
2               0.0               0.0            0.0       0.000000  
3               0.0               0.0            0.0       0.000000  
4               0.0               0.0            0.0       0.000000  

[5 rows x 47 columns]

In [123]:
# Split data into training and testing set
X4_1_train, X4_1_test, y4_train, y4_test = model_selection.train_test_split(df['moral_harm+'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X4_2_train, X4_2_test, y4_train, y4_test = model_selection.train_test_split(df['moral_harm-'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X4_3_train, X4_3_test, y4_train, y4_test = model_selection.train_test_split(df['moral_ingroup+'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X4_4_train, X4_4_test, y4_train, y4_test = model_selection.train_test_split(df['moral_ingroup-'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X4_5_train, X4_5_test, y4_train, y4_test = model_selection.train_test_split(df['moral_authority+'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X4_6_train, X4_6_test, y4_train, y4_test = model_selection.train_test_split(df['moral_authority-'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X4_7_train, X4_7_test, y4_train, y4_test = model_selection.train_test_split(df['moral_purity+'], df['requester_received_pizza'], test_size=0.1, random_state=42)
X4_8_train, X4_8_test, y4_train, y4_test = model_selection.train_test_split(df['moral_purity-'], df['requester_received_pizza'], test_size=0.1, random_state=42)

In [124]:
# Convert data frames to matrices
X4_1_train_vectorized = sp.csr_matrix(X4_1_train).transpose()
X4_2_train_vectorized = sp.csr_matrix(X4_2_train).transpose()
X4_3_train_vectorized = sp.csr_matrix(X4_3_train).transpose()
X4_4_train_vectorized = sp.csr_matrix(X4_4_train).transpose()
X4_5_train_vectorized = sp.csr_matrix(X4_5_train).transpose()
X4_6_train_vectorized = sp.csr_matrix(X4_6_train).transpose()
X4_7_train_vectorized = sp.csr_matrix(X4_7_train).transpose()
X4_8_train_vectorized = sp.csr_matrix(X4_8_train).transpose()

X4_1_test_vectorized = sp.csr_matrix(X4_1_test).transpose()
X4_2_test_vectorized = sp.csr_matrix(X4_2_test).transpose()
X4_3_test_vectorized = sp.csr_matrix(X4_3_test).transpose()
X4_4_test_vectorized = sp.csr_matrix(X4_4_test).transpose()
X4_5_test_vectorized = sp.csr_matrix(X4_5_test).transpose()
X4_6_test_vectorized = sp.csr_matrix(X4_6_test).transpose()
X4_7_test_vectorized = sp.csr_matrix(X4_7_test).transpose()
X4_8_test_vectorized = sp.csr_matrix(X4_8_test).transpose()

# Join each matrix to a single matrix
X4_train_vectorized = sp.hstack((X4_1_train_vectorized, X4_2_train_vectorized, X4_3_train_vectorized, X4_4_train_vectorized, X4_5_train_vectorized, X4_6_train_vectorized, X4_7_train_vectorized, X4_8_train_vectorized), format='csr')
X4_test_vectorized = sp.hstack((X4_1_test_vectorized, X4_2_test_vectorized, X4_3_test_vectorized, X4_4_test_vectorized, X4_5_test_vectorized, X4_6_test_vectorized, X4_7_test_vectorized, X4_8_test_vectorized), format='csr')

print(X4_train_vectorized.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.01492537 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.25       ... 0.         0.         0.        ]
 [0.         0.         0.05263158 ... 0.         0.         0.        ]]


In [133]:
# Classifier - Algorithm - SVM
# fit the training dataset on the classifier
SVM4 = svm.SVC(C=1.0, kernel='linear', class_weight = 'balanced')
SVM4.fit(X4_train_vectorized, y4_train)
# predict the labels on validation dataset
predictions_SVM4 = SVM4.predict(X4_test_vectorized)
# Use accuracy_score function to get the accuracy
print("SVM Accuracy Score -> ",accuracy_score(y4_test, predictions_SVM4)*100)

SVM Accuracy Score ->  72.1830985915493


In [135]:
#from sklearn.metrics import precision_score, recall_score, f1_score, roc_curve, auc, confusion_matrix
print('Accuracy Score: ', accuracy_score(y4_test, predictions_SVM4))
print('Precision Score: ', precision_score(y4_test, predictions_SVM4))
print('Recall Score: ', recall_score(y4_test, predictions_SVM4))
print('F1 Score: ', f1_score(y4_test, predictions_SVM4))
fpr, tpr, thresholds = roc_curve(y4_test, predictions_SVM4)
print('AUC Score: ', auc(fpr, tpr))
tn, fp, fn, tp = confusion_matrix(y4_test, predictions_SVM4).ravel()
print('Specificity: ', tn / (tn+fp))

Accuracy Score:  0.721830985915493
Precision Score:  0.2631578947368421
Recall Score:  0.03355704697986577
F1 Score:  0.05952380952380952
AUC Score:  0.5000720795758518
Specificity:  0.9665871121718377
